/**
 * Wraps learner source in a scope that captures console output and lets the
 * evaluator registry inspect values afterward, without ever touching the
 * DOM/network/globals of the page that's running the sandbox worker.
 *
 * Probe expressions are never learner input — they're generated by
 * packages/evaluators from curriculum-authored check configs (e.g.
 * `typeof score`, `score`, `add(2, 3)`), so inlining them verbatim carries
 * no injection risk from the learner's own code.
 */
export interface ProgramOptions {
  maxOutputBytes?: number
}

export function buildProgram(source: string, probeExpressions: string[], options: ProgramOptions = {}): string {
  const maxOutputBytes = Math.max(1, Math.floor(options.maxOutputBytes ?? 64 * 1024))
  const probeStatements = probeExpressions
    .map(
      (expr) => `
      try {
        let __probeValue = ${expr};
        if (__probeValue && typeof __probeValue.then === "function") {
          __probeValue = await __probeValue;
        }
        __probes[${JSON.stringify(expr)}] = { ok: true, value: __toJsonSafe(__probeValue) };
      } catch (__probeErr) {
        __probes[${JSON.stringify(expr)}] = { ok: false, error: __probeErr && __probeErr.message ? String(__probeErr.message) : String(__probeErr) };
      }`,
    )
    .join('\n')

  return `
"use strict";
return (async () => {
const __logs = [];
let __outputBytes = 0;
let __outputTruncated = false;
const __maxOutputBytes = ${maxOutputBytes};
function __utf8Size(text) {
  let bytes = 0;
  for (const char of text) {
    const point = char.codePointAt(0);
    bytes += point <= 0x7f ? 1 : point <= 0x7ff ? 2 : point <= 0xffff ? 3 : 4;
  }
  return bytes;
}
function __takeUtf8(text, byteLimit) {
  let result = "";
  let bytes = 0;
  for (const char of text) {
    const point = char.codePointAt(0);
    const size = point <= 0x7f ? 1 : point <= 0x7ff ? 2 : point <= 0xffff ? 3 : 4;
    if (bytes + size > byteLimit) break;
    result += char;
    bytes += size;
  }
  return { text: result, bytes };
}
function __stringifyLogArg(v) {
  if (typeof v === "string") return v;
  if (typeof v === "function") return "[Function]";
  if (typeof v === "undefined") return "undefined";
  try {
    const json = JSON.stringify(v);
    return typeof json === "string" ? json : String(v);
  } catch {
    try { return String(v); } catch { return "[Unprintable]"; }
  }
}
function __appendLog(args) {
  if (__outputTruncated) return;
  const line = args.map(__stringifyLogArg).join(" ");
  const separatorBytes = __logs.length > 0 ? 1 : 0;
  const remaining = __maxOutputBytes - __outputBytes - separatorBytes;
  if (remaining <= 0) { __outputTruncated = true; return; }
  const lineBytes = __utf8Size(line);
  if (lineBytes > remaining) {
    const partial = __takeUtf8(line, remaining);
    if (partial.text.length > 0) __logs.push(partial.text);
    __outputBytes += separatorBytes + partial.bytes;
    __outputTruncated = true;
    return;
  }
  __logs.push(line);
  __outputBytes += separatorBytes + lineBytes;
}
function __toJsonSafe(v) {
  if (typeof v === "function") return "[Function]";
  if (typeof v === "undefined") return undefined;
  try { return JSON.parse(JSON.stringify(v)); } catch { return String(v); }
}
const console = {
  log: (...args) => { __appendLog(args); },
  error: (...args) => { __appendLog(args); },
  warn: (...args) => { __appendLog(args); },
  info: (...args) => { __appendLog(args); },
};

try {
${source}

const __learnerLogs = __logs.slice();
const __learnerOutputTruncated = __outputTruncated;
const __probes = {};
${probeStatements}
return { logs: __learnerLogs, probes: __probes, outputTruncated: __learnerOutputTruncated };
} catch (__runtimeErr) {
  return {
    logs: __logs,
    probes: {},
    outputTruncated: __outputTruncated,
    runtimeError: __runtimeErr && __runtimeErr.message ? String(__runtimeErr.message) : String(__runtimeErr),
  };
}
})();
`
}
